# pull base image

FROM centos:7

#Maintainer
MAINTAINER MohammadMahdi Hafezieh <mm.hafezieh@gmail.com>

#=======yum update & python installation

RUN yum update -y
RUN yum -y install yum-utils
RUN yum -y install https://centos7.iuscommunity.org/ius-release.rpm
RUN yum -y install python36u
RUN python3.6 -V
RUN yum -y install python36u-pip
RUN pip3.6 install virtualenv

#=======install pip for build tool installation

RUN yum -y update; yum clean all
RUN yum -y install epel-release; yum clean all
RUN yum -y install python-pip; yum clean all

#=======install build tool (buildit)
RUN pip install buildit

#=======we can use -p [port-number] during docker run instead of EXPOSE
EXPOSE 8090

